create index if not exists profiles_updated_at_idx on public.profiles (updated_at);
create index if not exists applications_user_updated_at_idx on public.applications (user_id, updated_at desc);
create index if not exists documents_user_updated_at_idx on public.documents (user_id, updated_at desc);
alter table public.profiles enable row level security;
alter table public.applications enable row level security;
alter table public.documents enable row level security;
alter table public.ai_sessions enable row level security;
drop policy if exists "profiles owner access" on public.profiles;
drop policy if exists "applications owner access" on public.applications;
drop policy if exists "documents owner access" on public.documents;
drop policy if exists "ai sessions owner access" on public.ai_sessions;
drop policy if exists "profiles select own" on public.profiles;
drop policy if exists "profiles update own" on public.profiles;
drop policy if exists "applications select own" on public.applications;
drop policy if exists "applications insert own" on public.applications;
drop policy if exists "applications update own" on public.applications;
drop policy if exists "documents select own" on public.documents;
drop policy if exists "documents insert own" on public.documents;
drop policy if exists "documents update own" on public.documents;
drop policy if exists "documents delete own" on public.documents;
drop policy if exists "ai sessions select own" on public.ai_sessions;
drop policy if exists "ai sessions insert own" on public.ai_sessions;
drop policy if exists "ai sessions update own" on public.ai_sessions;
create policy "profiles select own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "profiles update own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "applications select own" on public.applications for select to authenticated using ((select auth.uid()) = user_id);
create policy "applications insert own" on public.applications for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "applications update own" on public.applications for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "documents select own" on public.documents for select to authenticated using ((select auth.uid()) = user_id);
create policy "documents insert own" on public.documents for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "documents update own" on public.documents for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "documents delete own" on public.documents for delete to authenticated using ((select auth.uid()) = user_id);
create policy "ai sessions select own" on public.ai_sessions for select to authenticated using ((select auth.uid()) = user_id);
create policy "ai sessions insert own" on public.ai_sessions for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "ai sessions update own" on public.ai_sessions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

